name: Build and Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./app/package-lock.json # ★ 追加
      - name: Install dependencies
        run: npm install
        working-directory: ./app
      - name: Copy imageList.json
        run: cp imageList.json ./app/src/assets/data/imageList.json

      - uses: snow-actions/git-config-user@v1.0.0
        with:
          name: ${{secrets.USER_NAME}}
          email: ${{secrets.USER_EMAIL}}
      - run: |
          set -x
          git add .
          git commit -m 'Update imageList.json' || true # エラーが出ても続行
          git push || true # エラーが出ても続行

      - name: Build
        run: npm run build
        working-directory: ./app
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./app/docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
