name: gitPush

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/gitPush.yml
  workflow_dispatch:

permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  pull-requests: read|write|none


jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: snow-actions/git-config-user@v1.0.0
        with:
          name:  ${{secrets.USER_NAME}}
          email: ${{secrets.USER_EMAIL}}
      - run: |
          set -x       
          git add .
          git commit -m 'Update imageList.json'
          git push origin main