name: gitPush
inputs:
  data:
    description: "追加するデータ"
    required: false #必須だとtrue?
    default: ""
  number:
    description: "削除する番号"
    required: false
    default: -1

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - .github/workflows/gitPush.yml
  workflow_dispatch:




jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
            
      - name: Run build script
        run: ./.github/scripts/test.sh > output.log
        with:
          data: data
          number: number
        shell: bash

      - uses: snow-actions/git-config-user@v1.0.0
        with:
          name:  ${{secrets.USER_NAME}}
          email: ${{secrets.USER_EMAIL}}
    
      - run: |
          set -x       
          git add .
          git commit -m 'Update imageList.json'
          git push