name: gitPush

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/gitPush.yml
      - metadata.json
    workflow_dispatch:

  permissions:
    contents:write

  jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: snow-actions/git-config-user@v1.0.0

      - name: Commit&Push
      - run: |
          set -x
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
       

          git add imageList.json
          git commit -m 'Update imageList.json'
          git push