name: gitPush

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/gitPush.yml
      - metadata.json
    workflow_dispatch:

  permissions:
    contents:write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Commit&Push
      - uses: snow-actions/git-config-user@v1.0.0
          with:
          name:  ${{secrets.USER_NAME}}
          email: ${{secrets.USER_EMAIL}}
      - run: |
          set -x
       
          git add imageList.json
          git commit -m 'Update imageList.json'
          git push